language : "de"
pipeline:
- name: "nlp_spacy"
  model: "de_core_news_sm"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
#- name: "intent_featurizer_spacy"
#- name: "intent_featurizer_count_vectors"
#- name: "components.intent_featurizers.TfIdfFeaturizer"
- name: "components.intent_featurizers.TfIdfCharWordFeaturizer"
- name: "intent_classifier_sklearn"
- name: "components.fallback_intent_filter.FallbackIntentFilter"
#- name: "ner_spacy"
#- name: "ner_duckling"
#  dimensions: ["time"]
- name: "ner_crf"
  BILOU_flag: false
- name: "ner_synonyms"